apiVersion: v1
kind: Service
metadata:
  name: myapp-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
    env: {{ .Values.env }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}