name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_DIR: ./task1/terraform

jobs:
  terraform:
    name: Validate & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
        run: terraform plan -detailed-exitcode

      - name: Import existing resources
        working-directory: ${{ env.TF_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
        run: |
          terraform import digitalocean_vpc.main 07b3173e-2024-4426-b053-051a7038e734 || true
          terraform import digitalocean_droplet.node 563095969 || true
          terraform import digitalocean_spaces_bucket.main fra1,turovets-bucket || true

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
        run: terraform apply -auto-approve